#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX

bspc config top_padding 20
bspc config border_width 2
bspc config normal_border_color \#d9d7ce
bspc config active_border_color \#ffcc66
bspc config focused_border_color \#ffa759
bspc config window_gap 10

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

bspc rule -a zathura state=tiled

#xinput set-prop 12 301 1
xinput set-prop 13 327 1

sxhkd &

(
	~/.screenlayout/default.sh 
	picom -b
	betterlockscreen -w dim
	~/.config/polybar/run.sh
) &

# Start recompiling wallpaper if itt's been changed
(
	betterlockscreen -u ~/.config/wall/wall.*
	betterlockscreen -w dim
) &
