#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX

bspc config top_padding         18
bspc config border_width         2
bspc config normal_border_color	\#d9d7ce
bspc config active_border_color	\#ffcc66
bspc config focused_border_color	\#ffa759
bspc config window_gap          6

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a zathura state=tiled

xrandr --newmode 1920x1080  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
xrandr --addmode eDP-1 1920x1080
xrandr --output eDP-1 --mode 1920x1080

sxhkd -r &
compton &
betterlockscreen -w dim &
(betterlockscreen -u ~/.config/wall/wall.*; betterlockscreen -w dim) &
~/.config/polybar/run.sh &
dex -a &
