# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/alex/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Alex's Configuration ------------------------------------

# Allow user-level npm global installs
PATH="$HOME/.node_modules/bin:$PATH"
export npm_config_prefix=~/.node_modules

# Install antigen if it doesn't exist
local antigen_path="$HOME/antigen.zsh"
if [ ! -f "$antigen_path" ]; then
  curl -L https://git.io/antigen -o "$antigen_path"
fi
source $antigen_path

antigen use oh-my-zsh
antigen bundle git
antigen bundle pip
antigen bundle command-not-found
antigen bundle aws
antigen bundle docker
antigen bundle docker-compose
antigen theme half-life
antigen bundle zsh-users/zsh-syntax-highlighting
antigen apply

bindkey -v
bindkey '^K' up-line-or-beginning-search
bindkey '^J' down-line-or-beginning-search

alias ls='ls --color=auto --group-directories-first'
alias ll='ls -hal'
alias l='ls -hl'
alias gs='git status'
alias vim='nvim'
alias startx='ssh-agent startx'
alias pip='echo "Nuh uh!"'
alias supip=/usr/bin/pip
alias clip='xclip -selection c'
alias yay='yay --color=always'
alias fehlast="find ~/Images/Screenshots | sort | tail -n 1 | xargs feh"

# Load local machine configuration
if [ -f ~/.zshrc_local ]; then
  source ~/.zshrc_local
fi
